eventor/core/models.py
# -*- encoding: utf-8 -*-
from datetime import datetime

from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.ext.hybrid import hybrid_property

from flask.ext.sqlalchemy import orm

from eventor import db
from eventor.core.utils import plural_name, slugify, underscorize


def raise_value(text):
    raise ValueError(text)


class CRUDMixin(object):
    """ Basic CRUD mixin
    """
    __table_args__ = {'extend_existing': True,
                      'mysql_charset': 'utf8',
                      'mysql_engine': 'InnoDB'}

    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    @declared_attr
    def __tablename__(cls):
        """ We want our app to be more English for pluralization cases
        """
        return plural_name(underscorize(cls.__name__))

    @classmethod
    def get(cls, id):
        return cls.query.get(id)

    @classmethod
    def create(cls, **kwargs):
        return cls(**kwargs).save()

    def update(self, commit=True, **kwargs):
        return self.__setattrs(**kwargs).save(commit)

    def save(self, commit=True):
        db.session.add(self)
        commit and db.session.commit()
        return self

    def delete(self, commit=True):
        db.session.delete(self)
        commit and db.session.commit()

    def __setattrs(self, **kwargs):
        for key in kwargs:
            key.startswith('_') and raise_value('Underscored values are not allowed')
            try:
                getattr(self, key)
                setattr(self, key, kwargs[key])
            except AttributeError:
                continue

        return self

    def as_dict(self, exclude=['password'], include=['*']):
        """ method for building dictionary for model value-properties filled
            with data from mapped storage backend
        """
        # columns = self._sa_class_manager
        # relations = [k for k in columns if isinstance(columns[k].property, orm.properties.RelationshipProperty)]
        columns = (p.key for p in self.__mapper__.iterate_properties if isinstance(p, orm.ColumnProperty))
        response = {}
        for col_name in columns:
            regular_name = col_name.startswith('_') and col_name[1:] or col_name
            response[regular_name] = regular_name not in exclude and getattr(self, regular_name)

        return response


class SlugMixin(CRUDMixin):
    """Basic mixin for models with slug and name
    """
    name = db.Column(db.Unicode(512), nullable=False)
    _slug = db.Column(db.String(128), nullable=False, unique=True)

    @hybrid_property
    def slug(self):
        return self._slug

    @slug.setter
    def slug(self, name):
        self._slug = slugify(name)

    def save(self, commit=True):
        self.slug = self.name
        return super(SlugMixin, self).save(commit)

    @classmethod
    def get_by_slug(cls, slug):
        return cls.query.filter_by(slug=slug).first()

    def __repr__(self):
        return "<%s:%s>" % (self.__class__.__name__,
                            self.name)


class Page(db.Model, SlugMixin):
    content = db.Column(db.UnicodeText)
    auth_required = db.Column(db.Boolean, default=False, nullable=False)

eventor/events/models.py
# -*- encoding: utf-8 -*-
from datetime import datetime
# from sqlalchemy.ext.associationproxy import association_proxy
# from sqlalchemy.ext.declarative import declared_attr

from eventor import db
# from eventor.auth.models import User

from eventor.core.models import CRUDMixin
from eventor.core.utils import plural_name, underscorize


__all__ = ['Event']

plural_under = lambda name: plural_name(underscorize(name))
lazy_cascade = {
    'lazy': 'dynamic',
    'cascade': 'all',
}


class EventStory(db.Model, CRUDMixin):
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    author = db.relationship('User', backref=db.backref('stories', **lazy_cascade), uselist=False)
    name = db.Column(db.Unicode(255), nullable=False)
    description = db.Column(db.UnicodeText, nullable=False)

    @property
    def active(self):
        return self.events.filter(Event.reg_starts <= datetime.utcnow(),
                                  Event.reg_ends >= datetime.utcnow())

    @property
    def archive(self):
        return self.events.except_(self.active)


events_managers = db.Table('events_managers', db.metadata,
    db.Column('event_id', db.Integer, db.ForeignKey('events.id'),
              primary_key=True),
    db.Column('user_id', db.Integer, db.ForeignKey('users.id'),
              primary_key=True),
)

event_participants = db.Table('events_participant', db.metadata,
    db.Column('event_id', db.Integer, db.ForeignKey('events.id'), primary_key=True),
    db.Column('user_id', db.Integer, db.ForeignKey('users.id'), primary_key=True),
    db.Column('p_type', db.Integer, default=0)
)


class Event(db.Model, CRUDMixin):
    name = db.Column(db.Unicode(255), nullable=False)
    description = db.Column(db.UnicodeText)
    starts_at = db.Column(db.DateTime, nullable=False)
    ends_at = db.Column(db.DateTime, nullable=False)
    reg_starts = db.Column(db.DateTime, nullable=False)
    reg_ends = db.Column(db.DateTime, nullable=False)

    story_id = db.Column(db.Integer, db.ForeignKey('event_stories.id'))
    storyline = db.relationship('EventStory', backref=db.backref('events', **lazy_cascade))

    # participants = association_proxy('p_users', 'user',
    #                 creator=lambda u: EventsParticipant(user_id=u.id))
    participants = db.relationship('User', secondary=event_participants,
                    backref='participant_for', passive_deletes=True)
    managers = db.relationship('User', secondary=events_managers,
                    backref='manager_for', passive_deletes=True)


#class EventsParticipant(db.Model):
#    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), primary_key=True)
#    event_id = db.Column(db.Integer, db.ForeignKey('events.id'), primary_key=True)
#    p_type = db.Column(db.Integer, default=0)
#    event = db.relationship(Event,
#                backref=db.backref("events_participant", cascade="all, delete-orphan"))
#    user = db.relationship("User")

eventor/events/forms.py
from flask import g
from flask.ext.wtf import (Form, TextAreaField, TextField, DateTimeField,
                           validators)
from .models import Event, EventStory


class EventForm(Form):
    name = TextField('Title', validators=[validators.Required()],
                      description="Title for an event is neccessary thing")
    description = TextAreaField('Description',
                    validators=[validators.Required()],
                    description="Here should come some interesting facts about your event")

    starts_at = DateTimeField('Starts at (DD.MM.YYYY HH:MM)',
                              format='%d.%m.%Y %H:%M',
                              validators=[validators.Required()],
                              description="DD.MM.YYYY HH:MM")
    ends_at = DateTimeField('Ends at (DD.MM.YYYY HH:MM)',
                            format='%d.%m.%Y %H:%M',
                            validators=[validators.Required()],
                            description="DD.MM.YYYY HH:MM")
    reg_starts = DateTimeField('Registration starts at (DD.MM.YYYY HH:MM)',
                               format='%d.%m.%Y %H:%M',
                               validators=[validators.Required()],
                               description="DD.MM.YYYY HH:MM")
    reg_ends = DateTimeField('Registration ends at (DD.MM.YYYY HH:MM)',
                             format='%d.%m.%Y %H:%M',
                             validators=[validators.Required()],
                             description="DD.MM.YYYY HH:MM")
    address = TextAreaField('Address', description="Input address details",
                            validators=[validators.Required()])
    max_participants = TextField('Participants limit',
                                 description='Max. participants')

    def save(self, obj=None, commit=True):
        ev = obj or Event()
        self.populate_obj(ev)
        g.user.manager_for.append(ev)
        return commit and ev.save() or ev


class EventStoryForm(Form):
    name = TextField('Title: *', description="Give a name to your event",
                    validators=[validators.Required()])
    description = TextAreaField('Description: *',
                    description="Place a couple of words to describe",
                    validators=[validators.Required()])

    def save(self, obj=None, commit=True):
        story = obj or EventStory()
        self.populate_obj(story)
        g.user.stories.append(story)
        return commit and story.save() or story

eventor/__init__.py
# -*- encoding: utf-8 -*-
import os
import sys

app_path = os.path.abspath(os.path.dirname(__file__))
app_path in sys.path or sys.path.insert(0, app_path)

from flask import Flask, g, send_from_directory
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.assets import Environment
from flask.ext.babel import Babel
from flask.ext.mail import Mail
from flask.ext.security import LoginForm, RegisterForm, current_user

from .main import vendor_js, user_js
import settings


app = Flask(__name__)
app.config.from_object(settings)
app.mail = Mail(app)

db = SQLAlchemy(app)
assets = Environment(app)
babel = Babel(app)

assets.register("vendor_js", vendor_js)
assets.register("user_js", user_js)

# from core import core
from auth import auth
from events import events
from core import core

app.register_blueprint(core)
app.register_blueprint(auth, url_prefix="/profile")
app.register_blueprint(events, url_prefix="/events")


@app.before_request
def setup_env():
    g.user = current_user
    app.jinja_env.globals['sign_in_form'] = LoginForm()
    app.jinja_env.globals['sign_up_form'] = RegisterForm()


@app.route('/crossdomain.xml')
def crossdomain():
    return send_from_directory(os.path.join(app.root_path, 'static'), 'crossdomain.xml', mimetype='text/xml')


@app.after_request
def inject_headers(response):
    response.headers['Access-Control-Allow-Origin'] = '*'
    return response

eventor/core/__init__.py
from flask import Blueprint

core = Blueprint('core', __name__)

import views

eventor/core/views.py
# -*- encoding: utf-8 -*-
from flask import abort, render_template, current_app
from jinja2.exceptions import TemplateNotFound

from . import core
# from .models import Page


@core.route("/")
def index():
    return render_template('base.html')


@core.route('/login')
def login():
    return render_template('auth/login.html')


@core.route('/templates/<path:template>')
@core.route('/templates/')
def template(template=None):
    template or abort(404)

    try:
        return render_template(current_app.jinja_env.get_template(template))
    except TemplateNotFound:
        abort(404)


# @core.route("/page/<slug>")
# def page(slug):
#     page = Page.query.filter_by(slug=slug).first_or_404()
#     if page.auth_required and g.user.is_anonymous():
#         abort(403)
#     return render_template("page.html", page=page)

eventor/events/__init__.py
from flask import Blueprint

events = Blueprint('events', __name__)


import views
import api

eventor/events/views.py
# -*- encoding: utf-8 -*-
import re
import trafaret as t
from flask import abort, g, render_template, request, redirect, Response, url_for
from flask.ext.security import login_required

from eventor import db
from eventor.auth.models import User
from eventor.core.utils import jsonify_status_code, json_dumps

from . import events
from eventor.events.forms import EventForm, EventStoryForm
from eventor.events.models import Event, EventStory
from eventor.core.utils import jsonify_status_code
from eventor import app

re_container = re.compile('event(?P<id>\d+)Container')

participant = t.Dict({'email': t.Email, 'first_name': t.String, 'last_name': t.String}).ignore_extra('*')


@events.route('/stories')
@login_required
def list_stories():
    return render_template("events/list_stories.html", stories=g.user.stories)


@events.route('/stories/create', methods=['GET', 'POST'])
@login_required
def create_story():
    story_form = EventStoryForm(request.form or None)

    if request.form and story_form.validate():
        story_form.save()
        return redirect(url_for('.list_stories'))

    return render_template('events/create_story.html', story_form=story_form)


@events.route('/stories/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def edit_story(id):
    story = EventStory.query.get_or_404(id)
    story_form = EventStoryForm(request.form or None, obj=story)

    if request.form and story_form.validate():
        story_form.save(story)
        return redirect(url_for('.list_stories'))

    return render_template('events/edit_story.html', story_form=story_form,
                           story=story)


@events.route('/stories/<int:id>/delete')
@login_required
def remove_story(id):
    story = EventStory.query.get_or_404(id)
    story.author == g.user or abort(403)
    story.delete()
    return redirect(url_for('.list_stories'))


@events.route('/stories/<int:id>/create', methods=['GET', 'POST'])
@login_required
def create_event(id):
    story = EventStory.query.get_or_404(id)
    form = EventForm(request.form or None)
    print request.form
    if request.form and form.validate():
        ev = form.save()
        story.events.append(ev)
        ev.save()
        return redirect(url_for('.show_event', id=ev.id))

    return render_template("events/create.html", story=story,
                           event_form=form)


@events.route('/<int:id>/')
@login_required
def show_event(id):
    event = Event.query.get_or_404(id)
    return render_template("events/show.html", event=event)


@events.route('/wdgt/')
def widget():
    c = request.args.get('c') or abort(404)
    matched = re_container.match(c) or abort(404)
    event_id = matched.groupdict()['id']
    response = Response(content_type="text/javascript")
    response.data = render_template('events/widget.js', container=c,
                                    event=Event.get(event_id))
    return response


@events.route('/check_participation/<int:id>')
def check_participation(id):
    """ Ajax handler for registered user
    """
    # g.user.is_anonymous()
    callback = request.args.get('callback', 'callback')
    response = {'response': 'ok', 'msg': 'registered'}

    event = Event.query.get_or_404(id)

    if g.user.is_anonymous():
        response = {'response': 'err', 'txt': 'not_registered'}
    elif g.user in event.participants:
        response = {'response': 'err', 'txt': 'already_registered'}
    else:
        response = {'response': 'ok',
                    'txt': {'first': g.user.first_name,
                            'last': g.user.last_name}}
    http_response = Response(content_type='text/javascript')
    http_response.data = "{}({})".format(callback, json_dumps(response))
    return http_response


@events.route('/attend/<int:id>', methods=['GET'])
def attend(id):
    callback = request.args.get('callback', 'callback')
    http_response = Response(content_type='text/javascript')
    response = {'response': 'ok', 'txt': 'You were saved as an event attendee'}
    event = Event.get(id)
    if g.user.is_anonymous():
        try:
            data = participant.check(request.args.to_dict())
            data.update({'password': 'test', 'roles': ['user']})
            u = User.create(**data)
            event.participants.append(u)
            db.session.commit()
        except t.DataError as e:
            response = {'response': 'err', 'txt': e.as_dict()}
    else:
        event.participants.append(g.user)
        db.session.commit()

    http_response.data = "{}({})".format(callback, json_dumps(response))
    return http_response

eventor/main.py
from flask.ext.assets import Bundle


vendor = {
    'prefix': "js/vendor/",
    'files': [
        'jquery-1.7.1.js',
        'underscore-1.3.3.js',
        'backbone-0.9.2.js',
        'chosen.jquery-0.9.8.js',
        'jquery.maskedinput.js',
        'handlebars-1.0.0.beta.6.js',
        'less-1.3.0.js',
        'bootstrap.js'
    ]
}


user = {
    'prefix': "coffee/",
    'files': [
        'common.coffee',
        'participants.coffee',
        'router.coffee'
    ]
}

user_js = Bundle(
    *[user['prefix'] + script for script in user['files']],
    filters="coffeescript",
    output="gen/user.js",
    debug=False
)

vendor_js = Bundle(
    *[vendor['prefix'] + script for script in vendor['files']],
    filters="uglifyjs",
    output="gen/vendor.js"
)

eventor/templates/_macro.html
{% macro base_field(field, class="input-medium") %}
<div class="control-group{% if field.errors %} error{% endif %}">
  {{ field.label(class='control-label') }}
  <div class="controls">
    {{ caller(field) }}
    {% if field.errors %}
      <span class="help-inline">{{ field.errors|join(' ') }}</span>
    {% endif %}
  </div>
</div>
{% endmacro %}

{% macro text_field(field, class="input-medium") %}
  {% call(field) base_field(field, class=class) %}
    {{ field(class=class, placeholder=field.description) }}
  {% endcall %}
{% endmacro %}

{% macro date_field(field, class="input-medium") %}
  {% call(field) base_field(field, class=class) %}
    <div class="input-append">
      {{ field(type='datetime-local', class=class, placeholder=field.description) }}<span class="add-on"><i class="icon-calendar"></i></span>
    </div>
  {% endcall %}
{% endmacro %}

{% macro check_field(field) %}
<div class="control-group">
  <div class="controls"><label class="checkbox">{{ field }}{{ field.label.text }}</label></div>
</div>
{% endmacro %}

{% macro base_form(form, action=".", field_class="input-medium", class="form-vertical", submit) %}
<form class="{{ class }}" method="post" action="{{ action }}">
  {{ caller(form) }}
</form>
{% endmacro %}

{% macro form_for(form, action=".", field_class="input-medium", class="form-vertical", submit="Go!") %}
  {% call(form) base_form(form, action=action, field_class=field_class, class=class, submit=submit) %}
      <fieldset>
        {%- for field in form -%}
          {%- if field.type in ['HiddenField', 'CSRFTokenField'] %}
            {{ field }}
          {% elif field.type == "BooleanField" %}
            {{ check_field(field) }}
          {% elif field.type == "DateTimeField" %}
            {{ date_field(field, class=field_class) }}
          {% elif field.type == 'SubmitField' %}

          {%- else %}
            {{ text_field(field, class=field_class) }}
          {% endif -%}
        {% endfor -%}
      </fieldset>
    <button type="submit" class="pull-right btn btn-inverse">{{ submit }}</button>
  {% endcall %}
{% endmacro %}

{% macro menu_el(endpoint) %}
  <li{% if request.endpoint == endpoint %} class="active"{% endif %}>{{ caller() }}</li>
{% endmacro %}

eventor/templates/base.html
<!DOCTYPE html>
{% from "_macro.html" import form_for, menu_el with context %}
{% if not page_title %}{% set page_title = "Hello and welcome, my dear friend!" %}{% endif %}
<html>
  <head>
    <title>{% block title %}{{ page_title }}{% endblock %} - Fancy Service</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <link rel="stylesheet/less" type="text/css" href="{{ url_for('static', filename="less/bootstrap.less") }}">
    <link rel="stylesheet/less" type="text/css" href="{{ url_for('static', filename="less/responsive.less") }}">
    <link rel="stylesheet/less" type="text/css" href="{{ url_for('static', filename="less/style.less") }}">
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    {% assets "vendor_js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    {% assets "user_js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/vendor/require-1.0.7.js') }}"></script>
  </head>
  <body>
    {% if g.user.is_anonymous() %}
      {% include "auth/_form_sign_in.html" %}
      {% include "auth/_form_sign_up.html" %}
    {% endif %}
    <div class="container">
      <ul class="nav nav-pills pull-right">
        {% call menu_el('auth.sign_in') %}
          <a href="{{ url_for('core.index') }}">Main</a>
        {% endcall %}
        <li><a href="#">About</a></li>
        <li><a href="#">Help</a></li>
        {% if g.user.is_anonymous() %}
        <li><a data-toggle="modal" href="#signUp">Sign Up</a></li>
        <li><a data-toggle="modal" href="#signIn">Login</a></li>
        {% else %}
        <li><a data-toggle="modal" href="{{ url_for('auth.profile') }}">Profile</a></li>
        <li><a data-toggle="modal" href="#signIn">Logout</a></li>
        {% endif %}
      </ul>
    </div>
    {% block content_wrapper %}
    <div class="container">
      <div class="row">
        <div class="span12 page-header">
          <h2>{{ self.title() }}</h2>
        </div>
      </div>
    </div>
    <div class="container">
      {% block content %}
      <div style="text-align: center; vertical-align: middle;">
        <p>Some nice text will be placed here</p>
      </div>
      {% endblock %}
    </div>
    {% endblock %}
    <!-- modals -->
  </body>
  {% block extra_js %}
  <script type="text/javascript">
    USERS_URL = "{{ url_for('events.participants') }}";
  (function($) {
    $(function() {
      $("ul.nav li.active i[class*='icon']").addClass("icon-white");
    });
  })(jQuery);
  </script>
  {% endblock %}
</html>

eventor/templates/base_auth.html
{% extends "base.html" %}


{% block content_wrapper %}
<div class="container">
  <div class="row">
    <div class="span2">
      <ul class="nav nav-list menu" style="padding-top: 8px;">
        <li class="nav-header">general</li>
        {% call menu_el('auth.profile') %}
          <a href="{{ url_for('auth.profile') }}">
            <i class="icon-home"></i> Profile
          </a>
        {% endcall %}
        {% call menu_el('events.list_stories') %}
          <a href="{{ url_for('events.list_stories') }}">
            <i class="icon-table"></i> Event's stories
          </a>
        {% endcall %}
        <li>
          <a href="{{ url_for('flask_security.logout') }}">
            <i class="icon-off"></i> Sign Out
          </a>
        </li>
      </ul>
    </div>
    <div class="span10">
      {% block content %}
      <h2>{{ self.title() }}</h2>
      {% endblock %}
    </div>
  </div>
</div>
{% endblock %}

eventor/templates/page.html
{% extends "base.html" %}

{% set page_title = page.name %}

{% block content %}
  <p>{{ page.content|safe() }}</p>
{% endblock content %}