eventor/core/models.py
# -*- encoding: utf-8 -*-
from datetime import datetime

from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.ext.hybrid import hybrid_property

from flask.ext.sqlalchemy import orm

from eventor import db
from eventor.core.utils import plural_name, slugify, underscorize


def raise_value(text):
    raise ValueError(text)


class CRUDMixin(object):
    """ Basic CRUD mixin
    """
    __table_args__ = {'extend_existing': True,
                      'mysql_charset': 'utf8',
                      'mysql_engine': 'InnoDB'}

    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    @declared_attr
    def __tablename__(cls):
        """ We want our app to be more English for pluralization cases
        """
        return plural_name(underscorize(cls.__name__))

    @classmethod
    def get(cls, id):
        return cls.query.get(id)

    @classmethod
    def create(cls, **kwargs):
        return cls(**kwargs).save()

    def update(self, commit=True, **kwargs):
        return self.__setattrs(**kwargs).save(commit)

    def save(self, commit=True):
        db.session.add(self)
        commit and db.session.commit()
        return self

    def delete(self, commit=True):
        db.session.delete(self)
        commit and db.session.commit()

    def __setattrs(self, **kwargs):
        for key in kwargs:
            key.startswith('_') and raise_value('Underscored values are not allowed')
            try:
                getattr(self, key)
                setattr(self, key, kwargs[key])
            except AttributeError:
                continue

        return self

    def as_dict(self, exclude=['password'], include=['*']):
        """ method for building dictionary for model value-properties filled
            with data from mapped storage backend
        """
        # columns = self._sa_class_manager
        # relations = [k for k in columns if isinstance(columns[k].property, orm.properties.RelationshipProperty)]
        columns = (p.key for p in self.__mapper__.iterate_properties if isinstance(p, orm.ColumnProperty))
        response = {}
        for col_name in columns:
            regular_name = col_name.startswith('_') and col_name[1:] or col_name
            response[regular_name] = regular_name not in exclude and getattr(self, regular_name)

        return response


class SlugMixin(CRUDMixin):
    """Basic mixin for models with slug and name
    """
    name = db.Column(db.Unicode(512), nullable=False)
    _slug = db.Column(db.String(128), nullable=False, unique=True)

    @hybrid_property
    def slug(self):
        return self._slug

    @slug.setter
    def slug(self, name):
        self._slug = slugify(name)

    def save(self, commit=True):
        self.slug = self.name
        return super(SlugMixin, self).save(commit)

    @classmethod
    def get_by_slug(cls, slug):
        return cls.query.filter_by(slug=slug).first()

    def __repr__(self):
        return "<%s:%s>" % (self.__class__.__name__,
                            self.name)


class Page(db.Model, SlugMixin):
    content = db.Column(db.UnicodeText)
    auth_required = db.Column(db.Boolean, default=False, nullable=False)

eventor/events/models.py
# -*- encoding: utf-8 -*-
from datetime import datetime
# from sqlalchemy.ext.associationproxy import association_proxy
# from sqlalchemy.ext.declarative import declared_attr

from eventor import db
# from eventor.auth.models import User

from eventor.core.models import CRUDMixin
from eventor.core.utils import plural_name, underscorize


__all__ = ['Event']

plural_under = lambda name: plural_name(underscorize(name))
lazy_cascade = {
    'lazy': 'dynamic',
    'cascade': 'all',
}


class EventStory(db.Model, CRUDMixin):
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    author = db.relationship('User', backref=db.backref('stories', **lazy_cascade), uselist=False)
    name = db.Column(db.Unicode(255), nullable=False)
    description = db.Column(db.UnicodeText, nullable=False)

    @property
    def active(self):
        return self.events.filter(Event.reg_starts <= datetime.utcnow(),
                                  Event.reg_ends >= datetime.utcnow())

    @property
    def archive(self):
        return self.events.except_(self.active)


events_managers = db.Table('events_managers', db.metadata,
    db.Column('event_id', db.Integer, db.ForeignKey('events.id'),
              primary_key=True),
    db.Column('user_id', db.Integer, db.ForeignKey('users.id'),
              primary_key=True),
)

event_participants = db.Table('events_participant', db.metadata,
    db.Column('event_id', db.Integer, db.ForeignKey('events.id'), primary_key=True),
    db.Column('user_id', db.Integer, db.ForeignKey('users.id'), primary_key=True),
    db.Column('p_type', db.Integer, default=0)
)


class Event(db.Model, CRUDMixin):
    name = db.Column(db.Unicode(255), nullable=False)
    description = db.Column(db.UnicodeText)
    starts_at = db.Column(db.DateTime, nullable=False)
    ends_at = db.Column(db.DateTime, nullable=False)
    reg_starts = db.Column(db.DateTime, nullable=False)
    reg_ends = db.Column(db.DateTime, nullable=False)

    story_id = db.Column(db.Integer, db.ForeignKey('event_stories.id'))
    storyline = db.relationship('EventStory', backref=db.backref('events', **lazy_cascade))

    # participants = association_proxy('p_users', 'user',
    #                 creator=lambda u: EventsParticipant(user_id=u.id))
    participants = db.relationship('User', secondary=event_participants,
                    backref='participant_for', passive_deletes=True)
    managers = db.relationship('User', secondary=events_managers,
                    backref='manager_for', passive_deletes=True)


#class EventsParticipant(db.Model):
#    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), primary_key=True)
#    event_id = db.Column(db.Integer, db.ForeignKey('events.id'), primary_key=True)
#    p_type = db.Column(db.Integer, default=0)
#    event = db.relationship(Event,
#                backref=db.backref("events_participant", cascade="all, delete-orphan"))
#    user = db.relationship("User")

eventor/events/forms.py
from flask import g
from flask.ext.wtf import (Form, TextAreaField, TextField, DateTimeField,
                           validators)
from .models import Event, EventStory


class EventForm(Form):
    name = TextField('Title', validators=[validators.Required()],
                      description="Title for an event is neccessary thing")
    description = TextAreaField('Description',
                    validators=[validators.Required()],
                    description="Here should come some interesting facts about your event")

    starts_at = DateTimeField('Starts at (DD.MM.YYYY HH:MM)',
                              format='%d.%m.%Y %H:%M',
                              validators=[validators.Required()],
                              description="DD.MM.YYYY HH:MM")
    ends_at = DateTimeField('Ends at (DD.MM.YYYY HH:MM)',
                            format='%d.%m.%Y %H:%M',
                            validators=[validators.Required()],
                            description="DD.MM.YYYY HH:MM")
    reg_starts = DateTimeField('Registration starts at (DD.MM.YYYY HH:MM)',
                               format='%d.%m.%Y %H:%M',
                               validators=[validators.Required()],
                               description="DD.MM.YYYY HH:MM")
    reg_ends = DateTimeField('Registration ends at (DD.MM.YYYY HH:MM)',
                             format='%d.%m.%Y %H:%M',
                             validators=[validators.Required()],
                             description="DD.MM.YYYY HH:MM")
    address = TextAreaField('Address', description="Input address details",
                            validators=[validators.Required()])
    max_participants = TextField('Participants limit',
                                 description='Max. participants')

    def save(self, obj=None, commit=True):
        ev = obj or Event()
        self.populate_obj(ev)
        g.user.manager_for.append(ev)
        return commit and ev.save() or ev


class EventStoryForm(Form):
    name = TextField('Title: *', description="Give a name to your event",
                    validators=[validators.Required()])
    description = TextAreaField('Description: *',
                    description="Place a couple of words to describe",
                    validators=[validators.Required()])

    def save(self, obj=None, commit=True):
        story = obj or EventStory()
        self.populate_obj(story)
        g.user.stories.append(story)
        return commit and story.save() or story

eventor/__init__.py
# -*- encoding: utf-8 -*-
import os
import sys

app_path = os.path.abspath(os.path.dirname(__file__))
app_path in sys.path or sys.path.insert(0, app_path)

from flask import Flask, g, send_from_directory
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.assets import Environment
from flask.ext.babel import Babel
from flask.ext.mail import Mail
from flask.ext.security import LoginForm, RegisterForm, current_user

from .main import vendor_js, user_js
import settings


app = Flask(__name__)
app.config.from_object(settings)
app.mail = Mail(app)

db = SQLAlchemy(app)
assets = Environment(app)
babel = Babel(app)

assets.register("vendor_js", vendor_js)
assets.register("user_js", user_js)

# from core import core
from auth import auth
from events import events
from core import core

app.register_blueprint(core)
app.register_blueprint(auth, url_prefix="/profile")
app.register_blueprint(events, url_prefix="/events")


@app.before_request
def setup_env():
    g.user = current_user
    app.jinja_env.globals['sign_in_form'] = LoginForm()
    app.jinja_env.globals['sign_up_form'] = RegisterForm()


@app.route('/crossdomain.xml')
def crossdomain():
    return send_from_directory(os.path.join(app.root_path, 'static'), 'crossdomain.xml', mimetype='text/xml')


@app.after_request
def inject_headers(response):
    response.headers['Access-Control-Allow-Origin'] = '*'
    return response

eventor/core/__init__.py
from flask import Blueprint

core = Blueprint('core', __name__)

import views

eventor/core/views.py
# -*- encoding: utf-8 -*-
from flask import abort, render_template, current_app
from jinja2.exceptions import TemplateNotFound

from . import core
# from .models import Page


@core.route("/")
def index():
    return render_template('base.html')


@core.route('/login')
def login():
    return render_template('auth/login.html')


@core.route('/templates/<path:template>')
@core.route('/templates/')
def template(template=None):
    template or abort(404)

    try:
        return render_template(current_app.jinja_env.get_template(template))
    except TemplateNotFound:
        abort(404)


# @core.route("/page/<slug>")
# def page(slug):
#     page = Page.query.filter_by(slug=slug).first_or_404()
#     if page.auth_required and g.user.is_anonymous():
#         abort(403)
#     return render_template("page.html", page=page)

eventor/events/__init__.py
from flask import Blueprint

events = Blueprint('events', __name__)


import views
import api

eventor/events/views.py
# -*- encoding: utf-8 -*-
import re
import trafaret as t
from flask import abort, g, render_template, request, redirect, Response, url_for
from flask.ext.security import login_required

from eventor import db
from eventor.auth.models import User
from eventor.core.utils import jsonify_status_code, json_dumps

from . import events
from eventor.events.forms import EventForm, EventStoryForm
from eventor.events.models import Event, EventStory
from eventor.core.utils import jsonify_status_code
from eventor import app

re_container = re.compile('event(?P<id>\d+)Container')

participant = t.Dict({'email': t.Email, 'first_name': t.String, 'last_name': t.String}).ignore_extra('*')


@events.route('/stories')
@login_required
def list_stories():
    return render_template("events/list_stories.html", stories=g.user.stories)


@events.route('/stories/create', methods=['GET', 'POST'])
@login_required
def create_story():
    story_form = EventStoryForm(request.form or None)

    if request.form and story_form.validate():
        story_form.save()
        return redirect(url_for('.list_stories'))

    return render_template('events/create_story.html', story_form=story_form)


@events.route('/stories/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def edit_story(id):
    story = EventStory.query.get_or_404(id)
    story_form = EventStoryForm(request.form or None, obj=story)

    if request.form and story_form.validate():
        story_form.save(story)
        return redirect(url_for('.list_stories'))

    return render_template('events/edit_story.html', story_form=story_form,
                           story=story)


@events.route('/stories/<int:id>/delete')
@login_required
def remove_story(id):
    story = EventStory.query.get_or_404(id)
    story.author == g.user or abort(403)
    story.delete()
    return redirect(url_for('.list_stories'))


@events.route('/stories/<int:id>/create', methods=['GET', 'POST'])
@login_required
def create_event(id):
    story = EventStory.query.get_or_404(id)
    form = EventForm(request.form or None)
    print request.form
    if request.form and form.validate():
        ev = form.save()
        story.events.append(ev)
        ev.save()
        return redirect(url_for('.show_event', id=ev.id))

    return render_template("events/create.html", story=story,
                           event_form=form)


@events.route('/<int:id>/')
@login_required
def show_event(id):
    event = Event.query.get_or_404(id)
    return render_template("events/show.html", event=event)


@events.route('/wdgt/')
def widget():
    c = request.args.get('c') or abort(404)
    matched = re_container.match(c) or abort(404)
    event_id = matched.groupdict()['id']
    response = Response(content_type="text/javascript")
    response.data = render_template('events/widget.js', container=c,
                                    event=Event.get(event_id))
    return response


@events.route('/check_participation/<int:id>')
def check_participation(id):
    """ Ajax handler for registered user
    """
    # g.user.is_anonymous()
    callback = request.args.get('callback', 'callback')
    response = {'response': 'ok', 'msg': 'registered'}

    event = Event.query.get_or_404(id)

    if g.user.is_anonymous():
        response = {'response': 'err', 'txt': 'not_registered'}
    elif g.user in event.participants:
        response = {'response': 'err', 'txt': 'already_registered'}
    else:
        response = {'response': 'ok',
                    'txt': {'first': g.user.first_name,
                            'last': g.user.last_name}}
    http_response = Response(content_type='text/javascript')
    http_response.data = "{}({})".format(callback, json_dumps(response))
    return http_response


@events.route('/attend/<int:id>', methods=['GET'])
def attend(id):
    callback = request.args.get('callback', 'callback')
    http_response = Response(content_type='text/javascript')
    response = {'response': 'ok', 'txt': 'You were saved as an event attendee'}
    event = Event.get(id)
    if g.user.is_anonymous():
        try:
            data = participant.check(request.args.to_dict())
            data.update({'password': 'test', 'roles': ['user']})
            u = User.create(**data)
            event.participants.append(u)
            db.session.commit()
        except t.DataError as e:
            response = {'response': 'err', 'txt': e.as_dict()}
    else:
        event.participants.append(g.user)
        db.session.commit()

    http_response.data = "{}({})".format(callback, json_dumps(response))
    return http_response

eventor/main.py
from flask.ext.assets import Bundle


vendor = {
    'prefix': "js/vendor/",
    'files': [
        'jquery-1.7.1.js',
        'underscore-1.3.3.js',
        'backbone-0.9.2.js',
        'chosen.jquery-0.9.8.js',
        'jquery.maskedinput.js',
        'handlebars-1.0.0.beta.6.js',
        'less-1.3.0.js',
        'bootstrap.js'
    ]
}


user = {
    'prefix': "coffee/",
    'files': [
        'common.coffee',
        'participants.coffee',
        'router.coffee'
    ]
}

user_js = Bundle(
    *[user['prefix'] + script for script in user['files']],
    filters="coffeescript",
    output="gen/user.js",
    debug=False
)

vendor_js = Bundle(
    *[vendor['prefix'] + script for script in vendor['files']],
    filters="uglifyjs",
    output="gen/vendor.js"
)

eventor/templates/events/create.html
{% extends "base_auth.html" %}
{% from "_macro.html" import base_form, text_field, date_field %}

{% set page_title = "Create something for &laquo;{}&raquo;?".format(story.name)|safe() %}

{% block content %}
  <h2>{{ self.title() }}</h2>
  {% call(event_form) base_form(event_form, class="form-vertical event") %}
    {{ event_form.csrf_token }}
    <fieldset>
      <div class="row">
        <div class="span6">
          <legend>Details</legend>
          {{ text_field(event_form.name, class="input-xxlarge") }}
          {{ text_field(event_form.description, class="input-xxlarge") }}
          {{ text_field(event_form.address, class="input-xxlarge") }}
        </div>
        <div class="span4">
          <legend>Event dates</legend>
          {{ date_field(event_form.starts_at) }}
          {{ date_field(event_form.ends_at) }}
          <legend>Registration limits</legend>
          {{ date_field(event_form.reg_starts) }}
          {{ date_field(event_form.reg_ends) }}
          {{ text_field(event_form.max_participants) }}
        </div>
      </div>
      <div class="row">
        <div class="form-actions">
          <button type="submit" class="pull-right btn btn-inverse">Go on, create!</button>
        </div>
      </div>
    </fieldset>
  {% endcall %}
{% endblock %}

eventor/templates/events/create_story.html
{% extends "base_auth.html" %}

{% from "_macro.html" import form_for %}

{% set page_title = "Add storyline" %}

{% block content %}
  <h2>{{ self.title() }}</h2>
  <div class="row">
    <div class="span6">
      {{ story_form.errors }}
      {{ form_for(story_form, action=url_for('events.create_story'),
                  field_class="input-xxlarge",
                  class="form-vertical story",
                  submit="Create your story!") }}
    </div>
  </div>
{% endblock %}

eventor/templates/events/edit_story.html
{% extends "base_auth.html" %}
{% from "_macro.html" import form_for %}
{% set page_title = "Editing: " + story.name %}

{% block content %}
  {{ super() }}
  <div class="row">
    <div class="span6">
      {{ form_for(story_form, action=url_for('.edit_story', id=story.id),
                  field_class="input-xxlarge",
                  class="form-vertical story",
                  submit="Save after all") }}
    </div>
  </div>
{% endblock %}

eventor/templates/events/list.html
{% extends "base_auth.html" %}
{% set page_title = "Here are your events storyline. Take it." %}


{% block content %}
  <h2>{{ self.title() }}<small><a href="{{ url_for('events.create') }}"><i class="icon-plus"></i></a></small></h2>
{% endblock %}

eventor/templates/events/list_stories.html
{% extends "base_auth.html" %}

{% set page_title = "Your storylines here" %}

{% macro inline_event(event) %}
  <li class="row event">
    <div class="span6"><a href="{{ url_for('.show_event', id=event.id) }}">{{ event.name }}</a></div>
    <div class="span2">
      {% if event.starts_at.strftime("%d.%m.%Y") == event.ends_at.strftime("%d.%m.%Y") %}
        {{ event.starts_at.strftime("%d.%m.%Y") }}
      {% else %}
        {{ event.starts_at.strftime("%d.%m.%Y") }} &mdash; {{ event.ends_at.strftime("%d.%m.%Y") }}
      {% endif %}
    </div>
    <div class="span1"><i class="icon-group" rel="tooltip" title="Participants"></i> &ndash; {{ event.participants|length() }}</div>
  </li>
{% endmacro %}

{% block content %}
  <div class="row storylines">
    <div class="span10">
      <h2 class="page-header">{{ self.title() }}<small><a href="{{ url_for('.create_story') }}"><i class="icon-plus"></i></a></small></h2>
    </div>
  </div>

  {% for story in stories %}
    <div class="row story font_12pt">
      <div class="span9">{{ story.name }}</div>
      <div class="span1 controls">
        <span class="badge badge-success">{{ story.active.count() }}</span>
        <a href="{{ url_for('.remove_story', id=story.id) }}"><i class="icon-trash"></i></a>
        <a href="{{ url_for('.edit_story', id=story.id) }}"><i class="icon-pencil"></i></a>
      </div>
    </div>
    <ul class="unstyled events">
      <li class="event">Active:</li>
      {% for event in story.active %}{{ inline_event(event) }}{% endfor %}
      <li class="event">Archived:</li>
      {% for event in story.archive %}{{ inline_event(event) }}{% else %}
        <li class="row event"><div class="span8"><i>There is no events found</i></div></li>
      {% endfor %}
    </ul>
  {% endfor %}

{% endblock %}

eventor/templates/events/show.html
{% extends "base_auth.html" %}

{% set page_title = event.name %}
{% block content %}
  <div class="row event">
    <h2 class="page-header">
      {{ self.title() }}
      <small>Story: <a href="{{ url_for('.list_stories') }}">{{ event.storyline.name }}</a></small>
    </h2>
    <div class="span7 description">
      <img src="http://placehold.it/150x150" class="push-left"/>
      {{ event.description }}
    </div>
    <div class="span3">
      <h3>Event schedule</h3>
      <dl>
        <dt>Start:</dt>
        <dd>{{ event.starts_at.strftime("%d.%m.%Y %H:%M") }}</dd>
        <dt>End:</dt>
        <dd>{{ event.ends_at.strftime("%d.%m.%Y %H:%M") }}</dd>
      </dl>
      <h3>Registration</h3>
      <dl>
        <dt>Start:</dt>
        <dd>{{ event.reg_starts.strftime("%d.%m.%Y %H:%M") }}</dd>
        <dt>End:</dt>
        <dd>{{ event.reg_ends.strftime("%d.%m.%Y %H:%M") }}</dd>
      </dl>
    </div>
  </div>

  <div class="participants">
  </div>
{% endblock %}